<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>23ff94c3-6fbb-47e9-9f8e-ba413db321ee</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.20.0" />
		<PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.5.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\TransactionManagement.BLL\TransactionManagement.BLL.csproj" />
	  <ProjectReference Include="..\TransactionManagement.DAL\TransactionManagement.DAL.csproj" />
	</ItemGroup>
</Project>
